Exception ignored in: <function Local.__del__ at 0x7f4ea9ed5700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f4ea9ed5700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f4ea9ed5700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Aug 19 16:45:39.166602 2020] [wsgi:error] [pid 148803] [remote 80.82.70.187:36994] Not Found: /cache/global/img/gs.gif
[Wed Aug 19 20:13:15.469445 2020] [wsgi:error] [pid 148801] [remote 83.97.20.29:45701] Not Found: /
[Wed Aug 19 20:17:25.229809 2020] [wsgi:error] [pid 148801] [remote 45.83.64.216:64996] Not Found: /
[Wed Aug 19 22:37:23.656977 2020] [wsgi:error] [pid 148803] [remote 223.105.4.249:39254] Not Found: /index.php
[Wed Aug 19 23:41:07.614049 2020] [wsgi:error] [pid 148801] [remote 185.39.11.105:60006] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fc6ccf8b670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdbdb700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdbdb700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdbdb700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdbdb700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc4e4d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc4e4d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Aug 20 00:09:26.261271 2020] [wsgi:error] [pid 156220] [remote 180.149.125.171:52218] Not Found: /
[Thu Aug 20 00:50:44.984501 2020] [wsgi:error] [pid 156220] [remote 185.173.35.37:42647] Not Found: /
[Thu Aug 20 01:06:48.717067 2020] [wsgi:error] [pid 156220] [remote 193.118.53.202:54798] Not Found: /
[Thu Aug 20 02:20:34.317406 2020] [wsgi:error] [pid 156222] [remote 80.82.70.187:33769] Not Found: /cache/global/img/gs.gif
[Thu Aug 20 06:20:53.075590 2020] [wsgi:error] [pid 156222] [remote 194.147.115.146:42494] Not Found: /
[Thu Aug 20 08:03:16.128091 2020] [wsgi:error] [pid 156220] [remote 185.39.11.105:41120] Not Found: /
[Thu Aug 20 12:00:24.391436 2020] [wsgi:error] [pid 156222] [remote 80.82.70.187:56663] Not Found: /cache/global/img/gs.gif
[Thu Aug 20 12:24:19.732394 2020] [wsgi:error] [pid 156220] [remote 192.35.168.249:52592] Not Found: /
[Thu Aug 20 12:24:20.490348 2020] [wsgi:error] [pid 156220] [remote 192.35.168.249:48382] Not Found: /
[Thu Aug 20 12:59:19.354821 2020] [wsgi:error] [pid 156220] [remote 184.105.247.194:27210] Not Found: /
[Thu Aug 20 13:52:35.525379 2020] [wsgi:error] [pid 156220] [remote 193.118.53.210:46350] Not Found: /
[Thu Aug 20 15:56:08.989994 2020] [wsgi:error] [pid 156220] [remote 185.41.240.21:37442] Not Found: /
[Thu Aug 20 18:04:54.593429 2020] [wsgi:error] [pid 156220] [remote 193.118.53.210:60512] Not Found: /
[Thu Aug 20 21:40:19.959118 2020] [wsgi:error] [pid 156222] [remote 80.82.70.187:50659] Not Found: /cache/global/img/gs.gif
[Thu Aug 20 22:01:01.574653 2020] [wsgi:error] [pid 156222] [remote 34.74.42.227:63697] Not Found: /
[Thu Aug 20 22:01:02.239013 2020] [wsgi:error] [pid 156222] [remote 34.74.42.227:64075] Not Found: /HNAP1/
[Thu Aug 20 23:28:34.069280 2020] [wsgi:error] [pid 156220] [remote 192.241.208.123:39494] Not Found: /cgi-bin/authLogin.cgi
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fc6cd115670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e3dc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e3dc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Aug 21 00:10:11.574826 2020] [wsgi:error] [pid 197595] [remote 139.162.79.87:51508] Not Found: /
[Fri Aug 21 00:10:52.582902 2020] [wsgi:error] [pid 197593] [remote 195.54.160.21:42948] Not Found: /index.php
[Fri Aug 21 00:12:11.904378 2020] [wsgi:error] [pid 197593] [remote 195.54.160.21:44512] Not Found: /
[Fri Aug 21 00:16:38.575931 2020] [wsgi:error] [pid 197593] [remote 195.54.160.21:50348] Not Found: /api/jsonws/invoke
[Fri Aug 21 01:11:06.095541 2020] [wsgi:error] [pid 197593] [remote 195.54.160.21:34680] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[Fri Aug 21 01:11:07.365503 2020] [wsgi:error] [pid 197593] [remote 195.54.160.21:45756] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[Fri Aug 21 01:22:09.800864 2020] [wsgi:error] [pid 197593] [remote 193.118.53.202:48324] Not Found: /
[Fri Aug 21 03:40:13.416341 2020] [wsgi:error] [pid 197593] [remote 83.97.20.29:6701] Not Found: /
[Fri Aug 21 06:13:09.605303 2020] [wsgi:error] [pid 197593] [remote 185.39.11.105:52476] Not Found: /
[Fri Aug 21 07:18:43.616967 2020] [wsgi:error] [pid 197595] [remote 80.82.70.187:38446] Not Found: /cache/global/img/gs.gif
[Fri Aug 21 09:11:07.427179 2020] [wsgi:error] [pid 197593] [remote 213.32.122.82:29487] Not Found: /
[Fri Aug 21 09:40:47.808078 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:5628] Not Found: /stalker_portal/c/version.js
[Fri Aug 21 09:40:51.682459 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:5758] Not Found: /client_area/
[Fri Aug 21 09:40:55.589707 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:5878] Not Found: /system_api.php
[Fri Aug 21 09:40:59.518967 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6070] Not Found: /streaming/clients_live.php
[Fri Aug 21 09:41:03.396420 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6234] Not Found: /stalker_portal/c/
[Fri Aug 21 09:41:07.281918 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6364] Not Found: /api.php
[Fri Aug 21 09:41:11.232125 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6448] Not Found: /login.php
[Fri Aug 21 09:41:18.998956 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6804] Not Found: /streaming
[Fri Aug 21 09:41:20.957798 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6906] Not Found: /streaming/clients_live.php
[Fri Aug 21 09:41:22.886541 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:6970] Not Found: /streaming/jcAE5h5s.php
[Fri Aug 21 09:41:26.752278 2020] [wsgi:error] [pid 197593] [remote 161.35.90.192:7132] Not Found: /
[Fri Aug 21 10:26:30.498132 2020] [wsgi:error] [pid 197593] [remote 161.35.73.221:40938] Not Found: /
[Fri Aug 21 10:26:36.716718 2020] [wsgi:error] [pid 197595] [remote 161.35.73.221:33614] Not Found: /
[Fri Aug 21 11:18:43.262124 2020] [wsgi:error] [pid 197593] [remote 213.52.128.29:55838] Not Found: /
[Fri Aug 21 12:49:01.152414 2020] [wsgi:error] [pid 197593] [remote 128.14.134.134:35124] Not Found: /
[Fri Aug 21 13:22:11.864367 2020] [wsgi:error] [pid 197593] [remote 192.241.237.171:49644] Not Found: /
[Fri Aug 21 14:15:33.473632 2020] [wsgi:error] [pid 197593] [remote 74.82.47.4:42874] Not Found: /
[Fri Aug 21 15:01:36.267131 2020] [wsgi:error] [pid 197595] [remote 185.216.140.186:37544] Not Found: /cache/global/img/gs.gif
[Fri Aug 21 17:01:14.999963 2020] [wsgi:error] [pid 197595] [remote 80.82.70.187:44575] Not Found: /cache/global/img/gs.gif
[Fri Aug 21 19:19:57.191634 2020] [wsgi:error] [pid 197593] [remote 185.39.11.105:46114] Not Found: /
[Fri Aug 21 20:15:41.506511 2020] [wsgi:error] [pid 197595] [remote 209.17.97.106:33251] Not Found: /
[Fri Aug 21 20:26:05.244004 2020] [wsgi:error] [pid 197595] [remote 185.39.11.84:41098] Not Found: /
[Fri Aug 21 22:51:01.232871 2020] [wsgi:error] [pid 197595] [remote 185.216.140.186:44314] Not Found: /cache/global/img/gs.gif
[Fri Aug 21 23:34:41.868074 2020] [wsgi:error] [pid 197593] [remote 139.162.116.133:53104] Not Found: /
[Fri Aug 21 23:44:51.338953 2020] [wsgi:error] [pid 197595] [remote 18.144.53.155:51466] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fc6cd115670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fc6cd115670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e1d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e1d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sat Aug 22 00:02:28.221418 2020] [wsgi:error] [pid 275614] [remote 209.17.96.98:37458] Not Found: /
[Sat Aug 22 01:36:33.415903 2020] [wsgi:error] [pid 275612] [remote 193.118.53.194:47448] Not Found: /
[Sat Aug 22 01:42:32.694310 2020] [wsgi:error] [pid 275614] [remote 185.39.11.84:36890] Not Found: /
[Sat Aug 22 02:14:12.367974 2020] [wsgi:error] [pid 275612] [remote 185.39.11.105:57330] Not Found: /
[Sat Aug 22 02:31:11.711678 2020] [wsgi:error] [pid 275612] [remote 185.39.11.105:49542] Not Found: /
[Sat Aug 22 02:39:01.338027 2020] [wsgi:error] [pid 275614] [remote 80.82.70.187:34373] Not Found: /cache/global/img/gs.gif
[Sat Aug 22 02:43:19.212873 2020] [wsgi:error] [pid 275614] [remote 83.97.20.34:25327] Not Found: /
[Sat Aug 22 04:32:46.731735 2020] [wsgi:error] [pid 275612] [remote 185.39.11.105:46728] Not Found: /
[Sat Aug 22 05:23:00.454686 2020] [wsgi:error] [pid 275614] [remote 92.118.160.57:43397] Not Found: /
[Sat Aug 22 06:10:15.791309 2020] [wsgi:error] [pid 275614] [remote 185.39.11.84:59018] Not Found: /
[Sat Aug 22 06:32:28.797384 2020] [wsgi:error] [pid 275612] [remote 192.241.237.130:43750] Not Found: /login
[Sat Aug 22 06:40:31.409792 2020] [wsgi:error] [pid 275614] [remote 185.216.140.186:43038] Not Found: /cache/global/img/gs.gif
[Sat Aug 22 07:12:50.636741 2020] [wsgi:error] [pid 275614] [remote 139.162.79.87:60432] Not Found: /
[Sat Aug 22 07:47:47.076149 2020] [wsgi:error] [pid 275612] [remote 185.39.11.105:56716] Not Found: /
[Sat Aug 22 08:08:58.450669 2020] [wsgi:error] [pid 275612] [remote 212.102.35.152:60370] Not Found: /index/index.php
[Sat Aug 22 10:24:07.586674 2020] [wsgi:error] [pid 275612] [remote 185.39.11.105:52308] Not Found: /
[Sat Aug 22 12:17:13.094879 2020] [wsgi:error] [pid 275614] [remote 80.82.70.187:44986] Not Found: /cache/global/img/gs.gif
[Sat Aug 22 13:45:32.753150 2020] [wsgi:error] [pid 275612] [remote 83.97.20.29:57655] Not Found: /
[Sat Aug 22 14:41:57.621021 2020] [wsgi:error] [pid 275612] [remote 216.218.206.66:65370] Not Found: /
[Sat Aug 22 14:59:19.821972 2020] [wsgi:error] [pid 275612] [remote 192.241.238.60:43672] Not Found: /owa/auth/logon.aspx
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fc6cd115670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cdce8700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e1e50>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fc6cc5e1e50>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fb9a7555700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fb9a7555700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sat Aug 22 18:37:16.541483 2020] [wsgi:error] [pid 2388] [remote 128.14.209.234:45852] Not Found: /
[Sat Aug 22 20:33:22.486606 2020] [wsgi:error] [pid 2388] [remote 196.52.43.117:33602] Not Found: /
[Sat Aug 22 21:32:18.642300 2020] [wsgi:error] [pid 2388] [remote 193.118.53.210:42570] Not Found: /
[Sat Aug 22 21:53:37.355389 2020] [wsgi:error] [pid 2390] [remote 80.82.70.187:44118] Not Found: /cache/global/img/gs.gif
[Sat Aug 22 23:12:39.859816 2020] [wsgi:error] [pid 2388] [remote 173.212.225.214:36966] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7fa559e25700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559e25700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa5591d5670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559e25700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559e25700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Aug 23 01:40:02.777909 2020] [wsgi:error] [pid 27427] [remote 192.241.237.31:59750] Not Found: /
[Sun Aug 23 01:54:32.988096 2020] [wsgi:error] [pid 27427] [remote 185.39.11.105:47528] Not Found: /
[Sun Aug 23 02:57:34.004960 2020] [wsgi:error] [pid 27429] [remote 106.75.24.162:52560] Not Found: /
[Sun Aug 23 03:16:30.458323 2020] [wsgi:error] [pid 27427] [remote 162.142.125.24:53394] Not Found: /
[Sun Aug 23 03:16:31.277968 2020] [wsgi:error] [pid 27427] [remote 162.142.125.24:37126] Not Found: /
[Sun Aug 23 04:19:19.201726 2020] [wsgi:error] [pid 27427] [remote 185.39.11.105:51958] Not Found: /
[Sun Aug 23 07:32:44.331197 2020] [wsgi:error] [pid 27429] [remote 80.82.70.187:56149] Not Found: /cache/global/img/gs.gif
[Sun Aug 23 07:49:58.729392 2020] [wsgi:error] [pid 27427] [remote 185.39.11.105:55998] Not Found: /
[Sun Aug 23 09:18:20.257832 2020] [wsgi:error] [pid 27427] [remote 193.118.53.202:34232] Not Found: /cgi-bin/config.exp
[Sun Aug 23 13:15:52.395554 2020] [wsgi:error] [pid 27427] [remote 74.82.47.5:39502] Not Found: /
[Sun Aug 23 15:04:53.899129 2020] [wsgi:error] [pid 27427] [remote 192.241.239.219:38706] Not Found: /owa/auth/logon.aspx
[Sun Aug 23 15:33:17.895154 2020] [wsgi:error] [pid 27427] [remote 139.162.116.133:38700] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7fa559f32700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559f32700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa55935f670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559f32700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa559f32700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f4e9ba75670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f4eb06cf700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f4eb06cf700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Aug 23 17:12:34.198135 2020] [wsgi:error] [pid 101817] [remote 80.82.70.187:43488] Not Found: /cache/global/img/gs.gif
[Sun Aug 23 19:09:44.253436 2020] [wsgi:error] [pid 101815] [remote 83.97.20.29:64995] Not Found: /
[Sun Aug 23 19:21:06.210782 2020] [wsgi:error] [pid 101815] [remote 192.35.168.249:34994] Not Found: /
[Sun Aug 23 19:21:06.965879 2020] [wsgi:error] [pid 101815] [remote 192.35.168.249:33596] Not Found: /
[Sun Aug 23 21:07:21.580845 2020] [wsgi:error] [pid 101817] [remote 192.241.143.125:55348] Not Found: /
[Sun Aug 23 21:07:22.017986 2020] [wsgi:error] [pid 101817] [remote 192.241.143.125:55391] Not Found: /HNAP1/
[Sun Aug 23 23:02:03.180575 2020] [wsgi:error] [pid 101815] [remote 125.64.94.134:37318] Not Found: /
[Sun Aug 23 23:47:39.717020 2020] [wsgi:error] [pid 101815] [remote 185.165.190.34:49464] Not Found: /
[Sun Aug 23 23:47:50.940205 2020] [wsgi:error] [pid 101815] [remote 185.165.190.34:53186] Not Found: /robots.txt
[Sun Aug 23 23:47:57.147244 2020] [wsgi:error] [pid 101815] [remote 185.165.190.34:55026] Not Found: /.well-known/security.txt
[Sun Aug 23 23:47:58.021324 2020] [wsgi:error] [pid 101815] [remote 185.165.190.34:55312] Not Found: /favicon.ico
[Sun Aug 23 23:48:11.282205 2020] [wsgi:error] [pid 101815] [remote 34.76.17.151:36635] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f881ecab670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881f906700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881f906700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881f906700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881f906700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e211d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e211d30>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Aug 24 00:53:19.529477 2020] [wsgi:error] [pid 139538] [remote 185.39.11.105:33696] Not Found: /
[Mon Aug 24 01:13:07.643966 2020] [wsgi:error] [pid 139538] [remote 122.228.19.79:32114] Not Found: /
[Mon Aug 24 02:41:54.648167 2020] [wsgi:error] [pid 139538] [remote 192.241.230.128:36582] Not Found: /
[Mon Aug 24 02:50:55.302350 2020] [wsgi:error] [pid 139540] [remote 80.82.70.187:33051] Not Found: /cache/global/img/gs.gif
[Mon Aug 24 09:21:08.679638 2020] [wsgi:error] [pid 139538] [remote 185.39.11.105:52450] Not Found: /
[Mon Aug 24 11:17:47.375626 2020] [wsgi:error] [pid 139540] [remote 185.39.11.105:59042] Not Found: /
[Mon Aug 24 12:30:30.239590 2020] [wsgi:error] [pid 139540] [remote 80.82.70.187:52326] Not Found: /cache/global/img/gs.gif
[Mon Aug 24 14:10:24.942965 2020] [wsgi:error] [pid 139538] [remote 184.105.139.68:43056] Not Found: /
[Mon Aug 24 17:11:10.316117 2020] [wsgi:error] [pid 139538] [remote 192.241.228.192:57582] Not Found: /owa/auth/logon.aspx
[Mon Aug 24 18:49:20.987480 2020] [wsgi:error] [pid 139538] [remote 162.142.125.40:47298] Not Found: /
[Mon Aug 24 18:49:21.781565 2020] [wsgi:error] [pid 139538] [remote 162.142.125.40:59648] Not Found: /
[Mon Aug 24 21:04:00.960191 2020] [wsgi:error] [pid 139538] [remote 128.14.134.170:44592] Not Found: /
[Mon Aug 24 22:06:25.932411 2020] [wsgi:error] [pid 139540] [remote 80.82.70.187:56922] Not Found: /cache/global/img/gs.gif
[Mon Aug 24 23:00:32.320669 2020] [wsgi:error] [pid 139538] [remote 185.39.11.105:52564] Not Found: /
[Mon Aug 24 23:39:50.307342 2020] [wsgi:error] [pid 139538] [remote 185.39.11.105:35454] Not Found: /
[Mon Aug 24 23:41:29.926264 2020] [wsgi:error] [pid 139538] [remote 188.166.5.156:45086] Not Found: /
[Mon Aug 24 23:41:38.945285 2020] [wsgi:error] [pid 139540] [remote 188.166.5.156:45264] Not Found: /
[Mon Aug 24 23:47:11.528457 2020] [wsgi:error] [pid 139538] [remote 192.35.168.96:1158] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f881ee40670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e30edc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e30edc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Aug 25 01:26:39.672423 2020] [wsgi:error] [pid 243795] [remote 139.162.79.87:51180] Not Found: /
[Tue Aug 25 03:02:30.774564 2020] [wsgi:error] [pid 243793] [remote 185.39.11.105:47638] Not Found: /
[Tue Aug 25 04:11:06.677435 2020] [wsgi:error] [pid 243793] [remote 180.149.125.165:55255] Not Found: /
[Tue Aug 25 05:13:29.064340 2020] [wsgi:error] [pid 243795] [remote 185.39.11.105:35918] Not Found: /
[Tue Aug 25 05:18:33.202996 2020] [wsgi:error] [pid 243793] [remote 192.241.228.142:51792] Not Found: /
[Tue Aug 25 07:46:20.555823 2020] [wsgi:error] [pid 243795] [remote 80.82.70.187:39030] Not Found: /cache/global/img/gs.gif
[Tue Aug 25 08:12:35.998156 2020] [wsgi:error] [pid 243793] [remote 83.97.20.29:19064] Not Found: /
[Tue Aug 25 12:18:04.315740 2020] [wsgi:error] [pid 243795] [remote 209.17.96.154:53336] Not Found: /
[Tue Aug 25 12:44:09.315055 2020] [wsgi:error] [pid 243793] [remote 216.218.206.67:48714] Not Found: /
[Tue Aug 25 13:02:49.668870 2020] [wsgi:error] [pid 243795] [remote 180.149.125.163:41970] Not Found: /
[Tue Aug 25 13:55:38.793152 2020] [wsgi:error] [pid 243793] [remote 128.14.134.170:33006] Not Found: /Telerik.Web.UI.WebResource.axd
[Tue Aug 25 15:13:23.648137 2020] [wsgi:error] [pid 243793] [remote 185.173.35.5:50443] Not Found: /
[Tue Aug 25 15:18:10.761690 2020] [wsgi:error] [pid 243793] [remote 54.219.183.76:43648] Not Found: /
[Tue Aug 25 17:24:28.850905 2020] [wsgi:error] [pid 243793] [remote 185.39.11.105:60428] Not Found: /
[Tue Aug 25 17:28:15.734344 2020] [wsgi:error] [pid 243795] [remote 80.82.70.187:37806] Not Found: /cache/global/img/gs.gif
[Tue Aug 25 17:37:03.218241 2020] [wsgi:error] [pid 243793] [remote 128.14.134.170:46566] Not Found: /remote/login
[Tue Aug 25 17:54:22.999803 2020] [wsgi:error] [pid 243793] [remote 192.241.223.234:58192] Not Found: /owa/auth/logon.aspx
[Tue Aug 25 20:59:52.819056 2020] [wsgi:error] [pid 243793] [remote 128.14.209.250:52910] Not Found: /
[Tue Aug 25 21:29:53.737392 2020] [wsgi:error] [pid 243795] [remote 196.52.43.118:49925] Not Found: /
[Tue Aug 25 23:43:32.399089 2020] [wsgi:error] [pid 243795] [remote 209.17.96.66:46236] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f881ee40670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881fa13700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e30fdc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f881e30fdc0>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Aug 26 00:01:07.434596 2020] [wsgi:error] [pid 334676] [remote 194.147.115.146:47786] Not Found: /
[Wed Aug 26 02:28:28.576573 2020] [wsgi:error] [pid 334674] [remote 193.118.55.146:48844] Not Found: /
[Wed Aug 26 02:31:45.455231 2020] [wsgi:error] [pid 334676] [remote 52.149.215.153:60587] Not Found: /
[Wed Aug 26 02:32:41.102384 2020] [wsgi:error] [pid 334674] [remote 185.39.11.105:49412] Not Found: /
[Wed Aug 26 03:05:17.177418 2020] [wsgi:error] [pid 334676] [remote 80.82.70.187:53382] Not Found: /cache/global/img/gs.gif
[Wed Aug 26 03:10:07.765889 2020] [wsgi:error] [pid 334674] [remote 178.154.200.171:44864] Not Found: /robots.txt
[Wed Aug 26 03:45:53.876417 2020] [wsgi:error] [pid 334674] [remote 128.14.134.170:51432] Not Found: /
[Wed Aug 26 04:40:42.690627 2020] [wsgi:error] [pid 334674] [remote 185.39.11.105:60580] Not Found: /
[Wed Aug 26 04:42:57.894294 2020] [wsgi:error] [pid 334676] [remote 192.35.168.203:37046] Not Found: /
[Wed Aug 26 04:42:58.279350 2020] [wsgi:error] [pid 334676] [remote 192.35.168.203:43876] Not Found: /
[Wed Aug 26 04:52:24.557295 2020] [wsgi:error] [pid 334676] [remote 185.216.140.186:54226] Not Found: /cache/global/img/gs.gif
[Wed Aug 26 05:17:17.761541 2020] [wsgi:error] [pid 334674] [remote 54.183.64.229:58298] Not Found: /owa/auth/logon.aspx
[Wed Aug 26 05:37:46.491703 2020] [wsgi:error] [pid 334674] [remote 192.241.221.204:36806] Not Found: /
[Wed Aug 26 06:26:43.638000 2020] [wsgi:error] [pid 334674] [remote 185.39.11.105:46084] Not Found: /
[Wed Aug 26 06:36:15.641833 2020] [wsgi:error] [pid 334676] [remote 194.147.115.146:48754] Not Found: /
[Wed Aug 26 07:07:16.496095 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:49662] Not Found: /
[Wed Aug 26 07:09:08.073061 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:39070] Not Found: /nmaplowercheck1598393347
[Wed Aug 26 07:09:08.689969 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:39676] Not Found: /evox/about
[Wed Aug 26 07:09:13.074968 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:39076] Not Found: /
[Wed Aug 26 07:09:13.142291 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:43080] Not Found: /HNAP1
[Wed Aug 26 07:09:13.699188 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:43532] Not Found: /sdk
[Wed Aug 26 07:09:19.200994 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:46900] Not Found: /
[Wed Aug 26 07:09:19.792088 2020] [wsgi:error] [pid 334676] [remote 185.100.87.191:47384] Not Found: /
[Wed Aug 26 08:08:39.704870 2020] [wsgi:error] [pid 334674] [remote 66.249.79.127:57446] Not Found: /robots.txt
[Wed Aug 26 10:12:26.049657 2020] [wsgi:error] [pid 334674] [remote 71.6.232.7:33194] Not Found: /
[Wed Aug 26 11:27:01.695289 2020] [wsgi:error] [pid 334674] [remote 87.227.173.90:43325] Not Found: /
[Wed Aug 26 11:27:01.919660 2020] [wsgi:error] [pid 334674] [remote 102.176.5.59:47727] Not Found: /login
[Wed Aug 26 12:39:46.902145 2020] [wsgi:error] [pid 334674] [remote 184.105.247.196:32732] Not Found: /
[Wed Aug 26 12:41:10.735136 2020] [wsgi:error] [pid 334674] [remote 54.67.76.206:35010] Not Found: /
[Wed Aug 26 12:54:30.668720 2020] [wsgi:error] [pid 334676] [remote 80.82.70.187:44872] Not Found: /cache/global/img/gs.gif
[Wed Aug 26 13:40:41.848656 2020] [wsgi:error] [pid 334674] [remote 193.118.53.194:59598] Not Found: /
