[Tue Jul 21 20:27:29.214297 2020] [wsgi:error] [pid 14805] [remote 175.193.7.139:10737] Not Found: /index.php
[Tue Jul 21 20:27:40.648532 2020] [wsgi:error] [pid 14805] [remote 175.193.7.139:10736] Not Found: /index.php
[Tue Jul 21 20:27:46.878884 2020] [wsgi:error] [pid 14805] [remote 175.193.7.139:10743] Not Found: /index.php
[Tue Jul 21 20:39:47.680022 2020] [wsgi:error] [pid 14805] [remote 175.193.7.139:11131] Not Found: /index.php
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f0bbbab5670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0bc0702700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0bc0702700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0bc0702700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 20:45:15.115553 2020] [wsgi:error] [pid 15466] [remote 65.154.226.109:16850] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7f0bc080f700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0bc080f700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 20:46:22.849857 2020] [wsgi:error] [pid 15578] [remote 65.154.226.109:39943] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7f0bc080f700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0bc080f700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 21:00:11.352456 2020] [wsgi:error] [pid 16738] [remote 185.39.11.105:33804] Not Found: /
[Tue Jul 21 21:04:59.572546 2020] [wsgi:error] [pid 16738] [remote 106.251.88.102:6487] Not Found: /
[Tue Jul 21 21:25:16.345691 2020] [php7:error] [pid 18177] [client 106.102.129.119:39508] script '/var/www/html/index.php' not found or unable to stat, referer: https://unqocn-api.hopto.org/
[Tue Jul 21 21:25:20.872665 2020] [php7:error] [pid 18177] [client 106.102.129.119:39508] script '/var/www/html/index.php' not found or unable to stat, referer: https://unqocn-api.hopto.org/
[Tue Jul 21 21:25:57.225369 2020] [php7:error] [pid 18251] [client 106.102.129.119:6902] script '/var/www/html/index.php' not found or unable to stat, referer: https://unqocn-api.hopto.org/
[Tue Jul 21 21:25:58.864486 2020] [php7:error] [pid 18251] [client 106.102.129.119:6902] script '/var/www/html/index.php' not found or unable to stat
[Tue Jul 21 21:27:41.088340 2020] [wsgi:error] [pid 18448] [remote 106.102.129.119:42660] Not Found: /index.php
[Tue Jul 21 21:27:41.527633 2020] [wsgi:error] [pid 18448] [remote 106.102.129.119:42660] Not Found: /favicon.ico
Exception ignored in: <function Local.__del__ at 0x7f3b391b7700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f3b391b7700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 21:28:28.783309 2020] [ssl:warn] [pid 18440] AH01909: unqocn-api.hopto.org:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 21 21:28:40.737513 2020] [wsgi:error] [pid 18551] [remote 106.102.129.119:17406] Not Found: /index.php
[Tue Jul 21 21:28:40.962105 2020] [wsgi:error] [pid 18551] [remote 106.102.129.119:17406] Not Found: /favicon.ico
[Tue Jul 21 21:30:01.500841 2020] [wsgi:error] [pid 18551] [remote 185.39.11.105:50016] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7f3b392c4700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f3b392c4700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 21:31:01.458762 2020] [wsgi:error] [pid 18751] [remote 106.102.129.119:55352] Not Found: /index.php/login
[Tue Jul 21 21:31:04.838423 2020] [wsgi:error] [pid 18751] [remote 106.102.129.119:55352] Not Found: /index.php
[Tue Jul 21 21:33:35.671112 2020] [wsgi:error] [pid 18751] [remote 106.102.129.119:63477] Not Found: /index.php
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f6952cd9670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f695391e700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f695391e700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 21:46:20.438018 2020] [wsgi:error] [pid 19671] [remote 106.102.129.119:48693] Not Found: /
[Tue Jul 21 21:46:20.822827 2020] [wsgi:error] [pid 19671] [remote 106.102.129.119:48693] Not Found: /favicon.ico
[Tue Jul 21 21:54:39.817011 2020] [wsgi:error] [pid 19669] [remote 93.174.93.139:50600] Not Found: /
[Tue Jul 21 22:03:29.635122 2020] [wsgi:error] [pid 19669] [remote 106.102.129.119:27757] Not Found: /index.php
[Tue Jul 21 22:08:43.270958 2020] [wsgi:error] [pid 19669] [remote 93.158.66.48:42370] Not Found: /.git/HEAD
[Tue Jul 21 22:08:44.537059 2020] [wsgi:error] [pid 19669] [remote 93.158.66.48:42538] Not Found: /.git/HEAD
[Tue Jul 21 22:08:46.918306 2020] [wsgi:error] [pid 19669] [remote 93.158.66.43:40428] Not Found: /.git/HEAD
[Tue Jul 21 22:08:48.192798 2020] [wsgi:error] [pid 19669] [remote 93.158.66.43:40656] Not Found: /.git/HEAD
[Tue Jul 21 22:08:48.762212 2020] [wsgi:error] [pid 19669] [remote 93.158.66.45:38826] Not Found: /.git/HEAD
[Tue Jul 21 22:08:50.028841 2020] [wsgi:error] [pid 19669] [remote 93.158.66.45:38994] Not Found: /.git/HEAD
[Tue Jul 21 22:15:15.408395 2020] [wsgi:error] [pid 19669] [remote 93.158.66.49:56048] Not Found: /.git/HEAD
[Tue Jul 21 22:15:16.711332 2020] [wsgi:error] [pid 19669] [remote 93.158.66.49:56266] Not Found: /.git/HEAD
[Tue Jul 21 22:16:20.199181 2020] [wsgi:error] [pid 19669] [remote 93.158.66.43:45010] Not Found: /.git/HEAD
[Tue Jul 21 22:16:21.438287 2020] [wsgi:error] [pid 19669] [remote 93.158.66.43:45468] Not Found: /.git/HEAD
[Tue Jul 21 22:30:38.670447 2020] [wsgi:error] [pid 19669] [remote 62.173.138.154:52951] Not Found: /
[Tue Jul 21 22:52:20.346597 2020] [wsgi:error] [pid 19669] [remote 185.39.11.105:38928] Not Found: /
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f0eef655670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f0eef655670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0ef429a700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0ef429a700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0ef429a700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f0ef429a700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f7601ce0670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f7602925700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f7602925700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 23:03:31.138698 2020] [wsgi:error] [pid 2128] [remote 117.111.28.16:31587] Not Found: /
[Tue Jul 21 23:03:31.498904 2020] [wsgi:error] [pid 2128] [remote 117.111.28.16:31587] Not Found: /favicon.ico
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fdc0c11e670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fdc0cd63700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fdc0cd63700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa662108670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa662d4d700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fa662d4d700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f264099e670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f26415e3700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f26415e3700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Jul 21 23:17:16.028469 2020] [wsgi:error] [pid 3450] [remote 67.205.165.53:32862] Not Found: /
[Tue Jul 21 23:17:16.242046 2020] [wsgi:error] [pid 3450] [remote 67.205.165.53:32862] Not Found: /
Exception ignored in: <function Local.__del__ at 0x7f26416dc700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f26416dc700>
Traceback (most recent call last):
  File "/home/django/unqocn_venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Jul 22 00:01:52.210881 2020] [wsgi:error] [pid 4879] [remote 185.39.11.105:36230] Not Found: /
[Wed Jul 22 00:10:55.235731 2020] [wsgi:error] [pid 4879] [remote 185.39.11.105:32940] Not Found: /
[Wed Jul 22 00:59:01.135592 2020] [wsgi:error] [pid 4881] [remote 80.82.70.187:45115] Not Found: /cache/global/img/gs.gif
[Wed Jul 22 03:32:23.985783 2020] [wsgi:error] [pid 4879] [remote 193.118.53.210:35318] Not Found: /
[Wed Jul 22 04:01:49.895659 2020] [wsgi:error] [pid 4879] [remote 93.174.93.139:55752] Not Found: /
[Wed Jul 22 05:27:15.837233 2020] [wsgi:error] [pid 4879] [remote 185.39.11.105:32872] Not Found: /
[Wed Jul 22 05:47:31.215048 2020] [wsgi:error] [pid 4879] [remote 162.243.128.91:52518] Not Found: /login
[Wed Jul 22 07:04:53.087165 2020] [wsgi:error] [pid 4879] [remote 185.39.11.105:43754] Not Found: /
[Wed Jul 22 08:05:44.352166 2020] [wsgi:error] [pid 4879] [remote 192.35.168.204:53274] Not Found: /
[Wed Jul 22 08:05:45.146211 2020] [wsgi:error] [pid 4879] [remote 192.35.168.204:37872] Not Found: /
[Wed Jul 22 08:28:16.551901 2020] [wsgi:error] [pid 4879] [remote 92.118.161.33:51435] Not Found: /
[Wed Jul 22 10:23:02.954056 2020] [wsgi:error] [pid 4879] [remote 192.168.219.105:2721] Not Found: /etc/intro.asp
[Wed Jul 22 10:23:03.082961 2020] [wsgi:error] [pid 4879] [remote 192.168.219.105:2721] Not Found: /favicon.ico
[Wed Jul 22 10:23:05.726987 2020] [wsgi:error] [pid 4879] [remote 192.168.219.105:2721] Not Found: /
[Wed Jul 22 10:23:11.391928 2020] [wsgi:error] [pid 4881] [remote 192.168.219.105:2731] Not Found: /
[Wed Jul 22 10:23:12.062356 2020] [wsgi:error] [pid 4881] [remote 192.168.219.105:2731] Not Found: /favicon.ico
[Wed Jul 22 10:24:49.041066 2020] [wsgi:error] [pid 4879] [remote 192.168.219.105:2862] Not Found: /
[Wed Jul 22 10:42:02.255639 2020] [wsgi:error] [pid 4881] [remote 80.82.70.187:60650] Not Found: /cache/global/img/gs.gif
